---
language: ruby
cache: bundler
bundler_args: --without development acceptance
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0"
